### ISSUE TITLE
Can we change all dependencies managed by bower to npm?

### ISSUE THREAD

**Issue by gitovers** [sahat/newedenfaces-react#13]
Since we already used npm, I don't really understand why we still need bower to manage other four dependencies(bootstrap/jquery/popup/toaster):smile:

**Comment by rfines** [comment]
Bower is for managing client side dependencies only, so things like Jquery that have no use on the server, cannot be installed through NPM but need to be managed through Bower.

**Comment by gitovers** [comment]
@rfines Thanks
