### ISSUE TITLE
console.log

### ISSUE THREAD

**Issue by YoungsoonLee** [sahat/newedenfaces-react#15]
thank you for example to learn react.
I can understand easily.

I have a question. I just wonder step by step fire and unfire react , alt or something,
So, I wrote "console.log('step1')" in the source (ex, components/AddCharacter.js) like a image 
![image](https://cloud.githubusercontent.com/assets/6457815/15023216/634080bc-11e4-11e6-875f-cd1092c958cf.png)

but there is no any log in devtool of Chrome  like this.
![image](https://cloud.githubusercontent.com/assets/6457815/15023238/8a1247a2-11e4-11e6-8006-a01bdac75978.png)

Could you teach me what's wrong with me?

**Comment by sahat** [comment]
@YoungsoonLee I see you closed this issue. What was wrong with the code?
