### ISSUE TITLE
$ is undefined

### ISSUE THREAD

**Issue by thenickcox** [sahat/newedenfaces-react#4]
In the [`FooterActions` call to `$.ajax`](https://github.com/sahat/newedenfaces-react/blob/master/app/actions/FooterActions.js#L12), I get

```
ReferenceError: $ is not defined
    at AltAction.getTopCharacters (/Users/macbookpro/Sites/nick-newedenfaces-react/app/actions/footeractions.js:12:5)
 ```

I had to wrap it in a `if (!typeof($) === 'undefined')` call, because it seems like jQuery isn't defined when it's being rendered on the server, but then gets defined by the time it renders on the client…? Is that expected?

**Comment by sahat** [comment]
If you clone this project, are you getting that error?

https://github.com/sahat/newedenfaces-react/blob/master/app/components/Footer.js#L15

`getTopCharacters` is invoked from within **componentDidMount** which does not get executed on the server, so you should never see $ is not defined error.

**Comment by thenickcox** [comment]
I cloned the project and didn't get that error, but I wasn't able to check the code out at that step. Feel free to close.
